export const receipts = [
  "Salário",
  "Aluguel Recebido",
  "Freelancer",
  "Distribuição Resultados",
  "Outras Receitas",
  "Transferência de contas",
  "Reembolsos e Adiantamentos",
  "Variação Cambial",
  "Aportes",
  "Resgates",
];

export const spends = [
  "Supermercado",
  "Almoços fora de casa",
  "Delivery",
  "Outros Alimentação",
  "Prestação carro",
  "Seguro do carro",
  "IPVA",
  "Combustível",
  "Estacionamentos e garagens",
  "Lavagem",
  "Manutenção em geral",
  "Transporte público",
  "Táxi/Uber",
  "Pedágios",
  "Multas",
  "Outros Transportes",
  "Médicos, dentistas e terapeutas",
  "Plano/Seguro de saúde",
  "Farmácia",
  "Medicamentos",
  "Atividades físicas",
  "Estética em geral",
  "Outros Saúde e Bem Estar",
  "Festas",
  "Bares, Restaurantes e Jantares",
  "Cinema/Teatro",
  "Mensalidade de clubes",
  "Viagens",
  "Futebol",
  "Outros Lazer",
  "Compras Diversas",
  "Roupas / Calçados",
  "Seguro de Vida",
  "Telefone celular",
  "Presentes",
  "Tarifas bancárias",
  "Doações",
  "Ajuda familiar",
  "Imprevistos em geral",
  "Taxas ",
  "Impostos",
  "Outros demais despesas",
  "Colégio",
  "Faculdade",
  "Livros",
  "Cursos",
  "Apps e Gadgets",
  "Condomínio",
  "Aluguel",
  "Prestação da casa",
  "IPTU",
  "Água",
  "Luz",
  "Telefone, internet e TV",
  "Gás",
  "Streaming",
  "Seguro patrimonial",
  "Despesas com animais",
  "Manutenções diversas",
  "Outros habitação",
];
