export const receipts = [
  "Salário",
  "Aluguel Recebido",
  "Freelancer",
  "Distribuição Resultados",
  "Outras Receitas",
  "Transferência de contas",
  "Reembolsos e Adiantamentos",
  "Variação Cambial",
  "Aportes",
  "Resgates",
];

export const spends = [
  "Supermercado",
  "Almoços fora de casa",
  "Delivery",
  "Outros Alimentação",
  "Prestação carro",
  "Seguro do carro",
  "IPVA",
  "Combustível",
  "Estacionamentos e garagens",
  "Lavagem",
  "Manutenção em geral",
  "Transporte público",
  "Táxi/Uber",
  "Pedágios",
  "Multas",
  "Outros Transportes",
  "Condomínio",
  "Aluguel",
  "Prestação da casa",
  "IPTU",
  "Água",
  "Luz",
  "Telefone, internet e TV",
  "Gás",
  "Streaming",
  "Seguro patrimonial",
  "Despesas com animais",
  "Manutenções diversas",
  "Outros habitação",
];
